sequenceDiagram
auteur ->>syesteme: Accède à la création d'article
syesteme -->>auteur: Affiche le formulaire de rédaction
auteur ->>syesteme: Remplit le formulaire (Titre, Catégorie, Statut, Image, Contenu) et enregistre
syesteme -->>auteur: Sauvegarde l'article et redirige vers la liste

