sequenceDiagram
    Auteur->>system: demande la page d’ajout d’article
    system-->>Auteur: afficher la page d'ajouter l'article
    Auteur->>system: remplire formulaire (titre ,categorie ,status ,image ,contenu) et enregistrer
    system-->>Auteur: sauvgarder l'article et rediriger vers la liste