usecase-beta

direction LR

actor Admin("Administrateur")
actor Auteur("Auteur")
actor Visiteur("Visiteur")

system [ "podcasting" ]

Admin -- "Consulter les catégories" -- system
Admin -- "Ajouter une catégorie" -- system
Admin -- "Modifier une catégorie" -- system
Admin -- "Supprimer une catégorie" -- system
Admin -- "Créer un auteur" -- system
Admin -- "Valider un article" -- system
Admin -- "Publier un article" -- system

Auteur -- "Ajouter un article" -- system
Auteur -- "Modifier un article non publié" -- system
Auteur -- "Supprimer un article non publié" -- system
Auteur -- "Changer son profil" -- system
Auteur -- "Réinitialiser son mot de passe" -- system

Visiteur -- "Consulter les articles" -- system